name: CI
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Build and Test Scala3 JS
        run: sbt +ringSeqJS/test
      - name: Build and Test Scala3 JVM
        run: sbt +ringSeqJVM/test
      - name: Scalafix
        run: sbt -v +"scalafixAll --check"
