name​: ​Test suite 

​on​: 
 ​ [push] 

​jobs​: 
  ​setup-test​: 
 ​   name​: ​Test library 
 ​   ​runs-on​: ​ubuntu-latest 
 ​   ​steps​: 
  
 ​   - ​name​: ​Checkout 
 ​     uses​: ​actions/checkout@v2 
  
 ​   - ​name​: ​Set up JDK 1.8 
 ​     uses​: ​actions/setup-java@v1 
 ​     ​with​: 
 ​       java-version​: ​1.8 
  
 ​   - ​name​: ​Compile 
 ​     ​run​: ​sbt compile
